version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            migrations: false
            host: mysql-db
            port: 3306
            user: root
            password: prisma
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
    - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql:
